name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Build, Push and Scan Docker Image"]
    types:
      - completed
    branches:
      - main

env:
  DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }}
  GCP_IMAGE: europe-west1-docker.pkg.dev/iron-wave-457510-e1/isen-python/myapp:dev-${{ github.sha }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLECLOUD_KEY }}"

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}

      - name: Tag image for Artifact Registry
        run: |
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.GCP_IMAGE }}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.GCP_IMAGE }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-cloud-run-service
          image: ${{ env.GCP_IMAGE }}
          region: europe-west1
          allow-unauthenticated: true
